#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.2'

networks:
  testNet:
    external:
      name: did_testNet

services:
  peer0IDP1:
    #container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:x86_64-1.0.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=did_testNet
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG

      - CORE_PEER_ID=peer0.idp1.example.com
      - CORE_PEER_LOCALMSPID=IDP1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_ADDRESS=peer0.idp1.example.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbIDP1:5984

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt

      #- CORE_PEER_GOSSIP_USELEADERELECTION=true
    #  - CORE_PEER_GOSSIP_ORGLEADER=false
    #  - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
    #  - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb1
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=myPassword1
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/idp1.example.com/users:/etc/hyperledger/crypto/msp/users

        - ./crypto-config/peerOrganizations/idp1.example.com/peers/peer0.idp1.example.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/idp1.example.com/peers/peer0.idp1.example.com/msp:/etc/hyperledger/crypto/peer/msp
        - ./crypto-config/peerOrganizations/idp1.example.com/peers/peer0.idp1.example.com/tls:/etc/hyperledger/crypto/peer/tls

    networks:
      testNet:
        aliases:
          - peer0.idp1.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  peer0IDP2:
    #container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:x86_64-1.0.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=did_testNet
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG


      - CORE_PEER_ID=peer0.idp2.example.com
      - CORE_PEER_LOCALMSPID=IDP2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_ADDRESS=peer0.idp2.example.com:7051


      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbIDP2:5984

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt

    #  - CORE_PEER_GOSSIP_USELEADERELECTION=true
  #    - CORE_PEER_GOSSIP_ORGLEADER=false
  #    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
  #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb2
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=myPassword2
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
        - 8051:7051
        - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/idp2.example.com/users:/etc/hyperledger/crypto/msp/users

        - ./crypto-config/peerOrganizations/idp2.example.com/peers/peer0.idp2.example.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/idp2.example.com/peers/peer0.idp2.example.com/msp:/etc/hyperledger/crypto/peer/msp
        - ./crypto-config/peerOrganizations/idp2.example.com/peers/peer0.idp2.example.com/tls:/etc/hyperledger/crypto/peer/tls

    networks:
      testNet:
        aliases:
          - peer0.idp2.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  peer0IDP3:
    #container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:x86_64-1.0.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=did_testNet
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG


      - CORE_PEER_ID=peer0.idp3.example.com
      - CORE_PEER_LOCALMSPID=IDP3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_ADDRESS=peer0.idp3.example.com:7051


      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbIDP3:5984

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt

    #  - CORE_PEER_GOSSIP_USELEADERELECTION=true
  #    - CORE_PEER_GOSSIP_ORGLEADER=false
  #    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
  #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb3
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=myPassword3
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
        - 9051:7051
        - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/idp3.example.com/users:/etc/hyperledger/crypto/msp/users

        - ./crypto-config/peerOrganizations/idp3.example.com/peers/peer0.idp3.example.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/idp3.example.com/peers/peer0.idp3.example.com/msp:/etc/hyperledger/crypto/peer/msp
        - ./crypto-config/peerOrganizations/idp3.example.com/peers/peer0.idp3.example.com/tls:/etc/hyperledger/crypto/peer/tls

    networks:
      testNet:
        aliases:
          - peer0.idp3.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  peer0AS1:
    #container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:x86_64-1.0.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=did_testNet
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG


      - CORE_PEER_ID=peer0.as1.example.com
      - CORE_PEER_LOCALMSPID=AS1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_ADDRESS=peer0.as1.example.com:7051


      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbAS1:5984

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt

    #  - CORE_PEER_GOSSIP_USELEADERELECTION=true
  #    - CORE_PEER_GOSSIP_ORGLEADER=false
  #    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
  #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb4
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=myPassword4
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
        - 10051:7051
        - 10053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/as1.example.com/users:/etc/hyperledger/crypto/msp/users

        - ./crypto-config/peerOrganizations/as1.example.com/peers/peer0.as1.example.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/as1.example.com/peers/peer0.as1.example.com/msp:/etc/hyperledger/crypto/peer/msp
        - ./crypto-config/peerOrganizations/as1.example.com/peers/peer0.as1.example.com/tls:/etc/hyperledger/crypto/peer/tls

    networks:
      testNet:
        aliases:
          - peer0.as1.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  peer0AS2:
    #container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:x86_64-1.0.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=did_testNet
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG


      - CORE_PEER_ID=peer0.as2.example.com
      - CORE_PEER_LOCALMSPID=AS2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_ADDRESS=peer0.as2.example.com:7051


      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbAS2:5984

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt

    #  - CORE_PEER_GOSSIP_USELEADERELECTION=true
  #    - CORE_PEER_GOSSIP_ORGLEADER=false
  #    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
  #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb5
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=myPassword5
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
        - 11051:7051
        - 11053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/as2.example.com/users:/etc/hyperledger/crypto/msp/users

        - ./crypto-config/peerOrganizations/as2.example.com/peers/peer0.as2.example.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/as2.example.com/peers/peer0.as2.example.com/msp:/etc/hyperledger/crypto/peer/msp
        - ./crypto-config/peerOrganizations/as2.example.com/peers/peer0.as2.example.com/tls:/etc/hyperledger/crypto/peer/tls

    networks:
      testNet:
        aliases:
          - peer0.as2.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  peer0RP1:
    #container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:x86_64-1.0.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=did_testNet
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG


      - CORE_PEER_ID=peer0.rp1.example.com
      - CORE_PEER_LOCALMSPID=RP1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_ADDRESS=peer0.rp1.example.com:7051


      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbRP1:5984

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt

    #  - CORE_PEER_GOSSIP_USELEADERELECTION=true
  #    - CORE_PEER_GOSSIP_ORGLEADER=false
  #    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
  #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb6
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=myPassword6
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
        - 12051:7051
        - 12053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/rp1.example.com/users:/etc/hyperledger/crypto/msp/users

        - ./crypto-config/peerOrganizations/rp1.example.com/peers/peer0.rp1.example.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/rp1.example.com/peers/peer0.rp1.example.com/msp:/etc/hyperledger/crypto/peer/msp
        - ./crypto-config/peerOrganizations/rp1.example.com/peers/peer0.rp1.example.com/tls:/etc/hyperledger/crypto/peer/tls

    networks:
      testNet:
        aliases:
          - peer0.rp1.example.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
